syntax = "All"
line_endings = "Windows"
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never"
space_after_function_names = "Never"
block_newline_gaps = "Never"
column_width = 100
indent_width = 2

[sort_requires]
enabled = false
