name: "Install luarocks"
inputs:
  luarocksVersion:
    description: Luarocks version
    required: true
  luaPath:
    description: Workspace relative path to Lua library
    required: true
  installPath:
    description: Workspace relative path wherein to install luarocks
    required: true
    default: ./.luarocks
runs:
  using: composite
  steps:
    - name: Restore luarocks install
      id: cache-luarocks-install-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.installPath }}
        key: ${{ runner.os }}-${{ runner.arch }}-luarocks-install

    - name: Setup variables
      id: globals
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: |
        echo "INST_PATH=${{ github.workspace }}/${{ inputs.installPath }}" >> "${GITHUB_OUTPUT}"
        echo "LUA_PATH=${{ github.workspace }}/${{ inputs.luaPath }}" >> "${GITHUB_OUTPUT}"

    - name: Download luarocks
      if: steps.cache-luarocks-install-restore.outputs.cache-hit != 'true'
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: |
        git clone --depth 1 --branch "v${{ inputs.luarocksVersion }}" https://github.com/luarocks/luarocks.git ../luarocks/

    - name: Compile luarocks (Unix)
      if: runner.os != 'Windows' && steps.cache-luarocks-install-restore.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ../luarocks
      run: |
        ./configure \
          --prefix="${{ steps.globals.outputs.INST_PATH }}" \
          --rocks-tree="${{ steps.globals.outputs.INST_PATH }}/systree" \
          --with-lua="${{ steps.globals.outputs.LUA_PATH }}"
        make && make install

    - name: Compile luarocks (Windows)
      if: runner.os == 'Windows' && steps.cache-luarocks-install-restore.outputs.cache-hit != 'true'
      shell: pwsh
      working-directory: ../luarocks
      run: |
        ./install.bat /MSVC /SELFCONTAINED /NOADMIN /Q /LUA "${{ steps.globals.outputs.LUA_PATH }}" /P "${{ steps.globals.outputs.INST_PATH }}"

    - name: Cache luarocks install directory
      if: steps.cache-luarocks-install-restore.outputs.cache-hit != 'true'
      id: cache-luarocks-install-save
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.installPath }}
        key: ${{ steps.cache-luarocks-install-restore.outputs.cache-primary-key }}

    - name: Set paths (Unix)
      if: runner.os != 'Windows'
      shell: bash
      working-directory: ${{ inputs.installPath }}
      run: |
        eval `./bin/luarocks path`

        echo LUA_CPATH="${LUA_CPATH}" >> ${GITHUB_ENV}
        echo LUA_PATH="${LUA_PATH}" >> ${GITHUB_ENV}
        echo PATH="${PATH}" >> ${GITHUB_ENV}

    - name: Set paths (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      working-directory: ${{ inputs.installPath }}
      run: |
        call luarocks.bat path > setenv.bat
        call setenv.bat

        echo LUA_CPATH=%LUA_CPATH% >> %GITHUB_ENV%
        echo LUA_PATH=%LUA_PATH% >> %GITHUB_ENV%
        echo PATH=%PATH% >> %GITHUB_ENV%

    - name: Check install
      shell: pwsh
      run: luarocks --version
