name: "Prepare environment"
inputs:
  nvim-rev:
    description: "Neovim version"
    required: true
runs:
  using: "composite"
  steps:
    - uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ inputs.nvim-rev }}

    - uses: ilammy/msvc-dev-cmd@v1
    - uses: leafo/gh-actions-lua@v12
      with:
        luaVersion: "5.1.5"

    - name: Setup Linux shell
      if: runner.os != 'Windows'
      shell: bash
      run: echo "SHELL=bash" >> "$GITHUB_ENV"

    - name: Setup Windows shell
      if: runner.os == 'Windows'
      shell: pwsh
      run: echo "SHELL=pwsh" >> "${Env:GITHUB_ENV}"

    - name: Install luarocks
      uses: ./.github/actions/install-luarocks
      with:
        luaPath: ./.lua

    - name: Restore luarocks dependencies
      id: cache-luarocks-deps-restore
      uses: actions/cache/restore@v4
      with:
        path: .luarocks/systree
        key: ${{ runner.os }}-${{ runner.arch }}--luarocks-deps

    - name: Prepare tests
      shell: ${{ env.SHELL }}
      run: luarocks test --prepare

    - name: Cache luarocks dependencies
      id: cache-luarocks-deps-save
      uses: actions/cache/save@v4
      with:
        path: .luarocks/systree
        key: ${{ steps.cache-luarocks-deps-restore.outputs.cache-primary-key }}

    - name: Check busted on path
      shell: ${{ env.SHELL }}
      run: busted --version
