name: "Install luarocks"
inputs:
  luarocksVersion:
    description: Luarocks version
    required: true
  luaPath:
    description: Workspace relative path to Lua library
    required: true
  installPath:
    description: Workspace relative path wherein to install luarocks
    required: true
    default: ./.luarocks
runs:
  using: composite
  steps:
    - name: Restore luarocks install
      id: cache-luarocks-install-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.installPath }}
        key: ${{ runner.os }}-${{ runner.arch }}-luarocks-install

    - name: Download luarocks
      if: steps.cache-luarocks-install-restore.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        git clone --depth 1 --branch "v${{ inputs.luarocksVersion }}" https://github.com/luarocks/luarocks.git ../luarocks/

    - name: Compile luarocks
      if: steps.cache-luarocks-install-restore.outputs.cache-hit != 'true'
      shell: pwsh
      working-directory: ../luarocks
      run: |
        ./install.bat /MSVC /SELFCONTAINED /NOADMIN /Q /LUA "${{ github.workspace }}/${{ inputs.luaPath }}" /P "${{ github.workspace }}/${{ inputs.installPath }}"

    - name: Cache luarocks install directory
      if: steps.cache-luarocks-install-restore.outputs.cache-hit != 'true'
      id: cache-luarocks-install-save
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.installPath }}
        key: ${{ steps.cache-luarocks-install-restore.outputs.cache-primary-key }}

    - name: Set paths
      shell: cmd
      working-directory: ${{ inputs.installPath }}
      run: |
        call luarocks.bat path > setenv.bat
        call setenv.bat

        echo LUA_CPATH=%LUA_CPATH% >> %GITHUB_ENV%
        echo LUA_PATH=%LUA_PATH% >> %GITHUB_ENV%
        echo PATH=%PATH% >> %GITHUB_ENV%

    - name: Check install
      shell: pwsh
      run: luarocks --version
