name: "Install luarocks"
inputs:
  luarocksVersion:
    description: Luarocks version
    required: true
  luaPath:
    description: Workspace relative path to Lua library
    required: true
  installPath:
    description: Workspace relative path to to install luarocks
    required: true
    default: ./.luarocks
runs:
  using: composite
  steps:
    - name: Download luarocks
      shell: pwsh
      env:
        LUAROCKS_TAG: v${{ inputs.luarocksVersion }}
      run: |
        git clone --depth 1 --branch ${Env:LUAROCKS_TAG} https://github.com/luarocks/luarocks.git ../luarocks/

    - name: Compile luarocks
      shell: pwsh
      env:
        LUA_DIR: ${{ github.workspace }}/${{ inputs.luaPath }}
        LUAROCKS_INSTALL_DIR: ${{ github.workspace }}/${{ inputs.installPath }}
      working-directory: ../luarocks
      run: |
        ./install.bat /MSVC /SELFCONTAINED /NOADMIN /Q /LUA ${Env:LUA_DIR} /P ${Env:LUAROCKS_INSTALL_DIR}

    - name: Set paths
      shell: cmd
      working-directory: ${{ inputs.installPath }}
      run: |
        echo TEST=10 >> %GITHUB_ENV%
        echo OTHER=FOO >> %GITHUB_ENV%

    # run: >
    #   luarocks path > %temp%\_lrp.bat && call %temp%\_lrp.bat && del
    #   %temp%\_lrp.bat && echo LUA_PATH=%LUA_PATH% >> %GITHUB_ENV% && echo
    #   LUA_CPATH=%LUA_CPATH% >> %GITHUB_ENV% && echo PATH=%PATH% >>
    #   %GITHUB_ENV%

    # - name: Check paths
    #   shell: pwsh
    #   run: ./.luarocks/luarocks.bat path
    #
    # - name: Set env
    #   shell: pwsh
    #   run: |
    #     foreach ($var in @("PATH", "LUA_PATH", "LUA_CPATH")) {
    #       $value = ((cat "../luarocks/install-out.txt" | Select-String -Pattern "^\s*$var\s*:\s*(.+)$").Matches | ForEach-Object {
    #         $_.Groups[1].Value.Trim()
    #       }) -join ';';
    #       Set-Variable -Name "$var" -Value "$value"
    #     };
    #     echo "${PATH}" >> ${Env:GITHUB_PATH};
    #     echo "LUA_CPATH=${LUA_CPATH};${Env:LUA_CPATH}" >> ${Env:GITHUB_ENV};
    #     echo "LUA_PATH=${LUA_PATH};${Env:LUA_PATH}" >> ${Env:GITHUB_ENV};

    - name: Check install
      shell: pwsh
      run: luarocks --version

    - name: Cleanup
      shell: pwsh
      run: rm -r ../luarocks
