name: "Install luarocks"
inputs:
  luarocksVersion:
    description: Luarocks version
    required: true
  luaPath:
    description: Workspace relative path to Lua library
    required: true
  installPath:
    description: Workspace relative path wherein to install luarocks
    required: true
    default: ./.luarocks
runs:
  using: composite
  steps:
    - name: Cache luarocks
      id: cache-luarocks
      uses: actions/cache@v4
      with:
        key: |
          ${{ runner.os }}-luarocks
        path: ${{ inputs.installPath }}

    - name: Download luarocks
      if: steps.cache-luarocks.outputs.cache-hit != 'true'
      shell: pwsh
      env:
        LUAROCKS_TAG: v${{ inputs.luarocksVersion }}
      run: |
        git clone --depth 1 --branch ${Env:LUAROCKS_TAG} https://github.com/luarocks/luarocks.git ../luarocks/

    - name: Compile luarocks
      if: steps.cache-luarocks.outputs.cache-hit != 'true'
      shell: pwsh
      env:
        LUA_DIR: ${{ github.workspace }}/${{ inputs.luaPath }}
        LUAROCKS_INSTALL_DIR: ${{ github.workspace }}/${{ inputs.installPath }}
      working-directory: ../luarocks
      run: |
        ./install.bat /MSVC /SELFCONTAINED /NOADMIN /Q /LUA ${Env:LUA_DIR} /P ${Env:LUAROCKS_INSTALL_DIR}

    - name: Set paths
      shell: cmd
      working-directory: ${{ inputs.installPath }}
      run: |
        call luarocks.bat path > setenv.bat
        call setenv.bat

        echo LUA_CPATH=%LUA_CPATH% >> %GITHUB_ENV%
        echo LUA_PATH=%LUA_PATH% >> %GITHUB_ENV%
        echo PATH=%PATH% >> %GITHUB_ENV%

    - name: Check install
      shell: pwsh
      run: luarocks --version
