-- Use the NeoVim runtime to generate a LuaLS rc file.

local rtps = {
	"./lua/?.lua",
	"./lua/?/init.lua",
	"?.lua",
}

local lua_path = os.getenv("LUA_PATH")

-- Add all items in LUA_PATH (if it exists)
if lua_path ~= nil then
	rtps = vim.list_extend(rtps, vim.split(lua_path, ";", { trimempty = true }))
end

local libs = {
	"./lua/_meta",
}

-- Add addons
for _, dir in ipairs({ "busted", "luassert" }) do
	table.insert(libs, vim.fs.abspath(("./lua-ls-plugins/%s/library"):format(dir)))
end

-- Add neovim runtime paths (For best reproducability, execute this script with the --clean flag)
libs = vim.list_extend(libs, vim.api.nvim_get_runtime_file("", true))

-- Generated by CI
local ignore_dirs = {
	".lua",
	".luarocks",
}

-- Ignore plenary...
if lua_path ~= nil then
	for _, path in ipairs(vim.split(lua_path, ";", { trimempty = true, plain = true })) do
		local dir = vim.fs.normalize(vim.fs.dirname(path))
		for _, match in ipairs(vim.fs.find("plenary", { type = "directory", path = dir })) do
			vim.print(("Found plenary at: '%s', adding to ignore list..."):format(match))
			table.insert(ignore_dirs, match)
		end
	end
end

-- Determine luarocks 'share' path (if luarocks is available)
if vim.fn.executable("luarocks") == 1 then
	local result = vim.system({ "luarocks", "config", "deploy_lua_dir" }):wait()
	if result.code == 0 then
		table.insert(libs, vim.trim(result.stdout))
	end
end

local luarc = {
	["$schema"] = "https://raw.githubusercontent.com/LuaLS/vscode-lua/master/setting/schema.json",
	runtime = {
		path = vim.tbl_map(vim.fs.normalize, rtps),
		pathStrict = true,
	},
	workspace = {
		ignoreDir = ignore_dirs,
		library = vim.tbl_map(vim.fs.normalize, libs),
	},
	userThirdParty = { vim.fs.normalize(vim.fs.abspath("./lua-ls-addons")) },
}

io.stdout:write(vim.json.encode(luarc))
