name: Check typing
env:
  TEST_PLUGIN_PATH: "~/nvim-plugins/"

on:
  pull_request:
    branches:
      - master
jobs:
  unit_tests:
    name: lua-language-server check
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.11.0

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - uses: actions/cache@v4
        id: cache
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/nvim-plugins
          key: ${{ runner.os }}-nvim-plugins

      - name: Install nvim plugins
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p $TEST_PLUGIN_PATH
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ${TEST_PLUGIN_PATH}plenary.nvim
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter ${TEST_PLUGIN_PATH}treesitter

      - name: Prepare
        run: |
          brew install lua-language-server

      - name: Check types
        run: |
          echo "Checking types in: $(pwd)"
          lua-language-server --version
          make type-check
